when:
  - branch: main
    event: [push, manual]
steps:
  - name: commit time
    image: alpine/git
    depends_on: []
    commands:
      - git log -1 --format=%ct > frontend/.commit-time

  - name: backend checks
    image: ghcr.io/pnpm/pnpm:11
    depends_on: []
    commands:
      - pnpm runtime set node 26 -g
      - cd backend
      - pnpm i --frozen-lockfile
      - pnpm run fmt:check
      - pnpm run lint
      - pnpm exec tsc --noEmit

  - name: frontend checks
    image: ghcr.io/pnpm/pnpm:11
    depends_on: []
    commands:
      - pnpm runtime set node 26 -g
      - cd frontend
      - pnpm i --frozen-lockfile
      - pnpm run gen:api
      - pnpm run types
      - pnpm run fmt:check
      - pnpm run lint
      - pnpm exec tsc --noEmit

  - name: build
    image: woodpeckerci/plugin-docker-buildx@sha256:e8df33f35247d448d21aa2c4b500e3809c117b9fb64233eadcf640ba00d8690b
    depends_on:
      - commit time
    settings:
      dry_run: true
      registry: forgejo.isbl.cz
      repo: forgejo.isbl.cz/isabella/songbook
      platforms: linux/arm64
      cache_images:
        - cache.isbl.cz/songbook:cache
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password

  - name: push
    image: woodpeckerci/plugin-docker-buildx@sha256:e8df33f35247d448d21aa2c4b500e3809c117b9fb64233eadcf640ba00d8690b
    depends_on:
      - backend checks
      - frontend checks
      - build
      - commit time
    settings:
      registry: forgejo.isbl.cz
      repo: forgejo.isbl.cz/isabella/songbook
      tags:
        - latest
        - sha-${CI_COMMIT_SHA:0:8}
      platforms: linux/arm64
      cache_images:
        - cache.isbl.cz/songbook:cache
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password
