service: songbook-functions

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  location: West Europe

plugins:
  - serverless-azure-functions

package:
  individually: true
  exclude:
    - '**/*'
  include:
    - graphql-function.json
    - handler.js

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http: true
        path: /graphql
        x-azure-settings:
          authLevel: anonymous
  #graphiql:
  #  handler: graphiql.run
  #  events:
  #    - http: true
  #      path: /graphql
  #      method: GET
