name: Prepare the repo to be worked with

runs:
  using: 'composite'
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run in devshell-ish
      shell: bash
      run: |
        export PATH=`nix develop -c bash -c 'echo $PATH'`
        echo PATH=$PATH >> ${GITHUB_ENV}


    - name: 🙈 Cache
      uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: ${{ hashFiles('yarn.lock') }}
    - name: 📥 Install deps
      shell: bash
      run: |
        yarn config set enableGlobalCache 0
        yarn config set cacheFolder .yarn/cache
        yarn --immutable
